"""Assignment-local workspace discovery and boundary enforcement."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


class WorkspaceError(RuntimeError):
    """Raised when an assignment workspace is invalid or out of bounds."""


INIT_DIRECTORIES = (
    "outline",
    "sources",
    ".loop",
    ".loop/sections",
    ".loop/reviews",
    ".loop/logs",
    ".loop/tasks",
    ".loop/agent-results",
    "output",
)

INIT_FILES = {
    "assignment.md": """# Assignment

<!-- Replace this template with the complete assignment prompt and requirements. -->

## Task

Describe the task to complete.

## Requirements

- Add the requirements, constraints, and due-date details here.
""",
    "sources/links.md": """# Sources

<!-- Add the HTTP(S) links Loop may use as sources, one per line or as Markdown links. -->
""",
    "README.md": """# This Loop workspace

This folder is an assignment workspace for Loop. Keep the assignment prompt,
guidance, and source links here so the workflow can use one self-contained
workspace.

## Set up the assignment

1. Replace the template in `assignment.md` with the full assignment prompt,
   requirements, constraints, and deliverable details.
2. Put the assignment brief, outline, rubric, and class guidance in `outline/`.
3. Add the HTTP(S) sources Loop may cite to `sources/links.md` as Markdown links
   or plain URLs, one per line.
4. Put optional past grades or professor feedback in `sources/` as PDF, DOCX,
   Markdown, or text files. These are guidance only and are not cited as
   sources.

## Run Loop

From this folder, ask Loop to complete the assignment:

```bash
loop run . --runtime conversation --request "Complete the assignment in this folder using the supplied sources."
```

The conversation runtime pauses when it needs a native Codex/ChatGPT Work
subagent. Follow the task manifest in `.loop/tasks/`, mark the task complete,
and resume the run as described by the Loop skill. For a local smoke test that
does not use model access, run `loop run . --runtime demo` instead.

Useful commands:

```bash
loop status .
loop tasks . --json
loop log . --tail 50
loop pause .
loop resume .
```

Loop writes intermediate state under `.loop/` and final deliverables under
`output/`. Do not edit `.loop/` artifacts by hand; update the assignment inputs
and resume the workflow instead.

This README is generated by `loop init <assignment-name>`. Running
`loop init <same-assignment-name>` again from the class directory is safe: it
creates missing folders and starter files without overwriting your work.
""",
}


@dataclass(frozen=True)
class InitResult:
    """The files and directories affected by ``loop init``."""

    root: str
    created: tuple[str, ...]
    existing: tuple[str, ...]

    @property
    def message(self) -> str:
        lines = [f"Loop workspace ready: {self.root}"]
        if self.created:
            lines.append("Created:")
            lines.extend(f"  {path}" for path in self.created)
        if self.existing:
            lines.append("Preserved:")
            lines.extend(f"  {path}" for path in self.existing)
        return "\n".join(lines)


@dataclass(frozen=True)
class Workspace:
    # Markdown is included because it is a plain-text feedback format; the
    # required links.md is excluded by path and remains the only source list.
    SOURCE_FEEDBACK_EXTENSIONS = frozenset({".docx", ".md", ".pdf", ".text", ".txt"})
    _MARKDOWN_LINK_RE = re.compile(r"\[[^\]]*\]\((https?://[^\s)]+)\)", re.IGNORECASE)
    _URL_RE = re.compile(r"https?://[^\s<>\[\]()]+", re.IGNORECASE)

    root: Path
    loop_dir: Path
    output_dir: Path

    @classmethod
    def discover(cls, path: str | Path = ".") -> "Workspace":
        candidate = Path(path).expanduser().resolve()
        if not candidate.exists():
            raise WorkspaceError(f"assignment directory does not exist: {candidate}")
        if not candidate.is_dir():
            raise WorkspaceError(f"assignment path is not a directory: {candidate}")
        return cls(candidate, candidate / ".loop", candidate / "output")

    @classmethod
    def initialize_named(
        cls, assignment_name: str, parent: str | Path = "."
    ) -> InitResult:
        """Create a named assignment directory below the current class folder."""

        name = Path(assignment_name)
        if (
            name.is_absolute()
            or len(name.parts) != 1
            or name.parts[0] in {".", ".."}
            or "\x00" in assignment_name
        ):
            raise WorkspaceError(
                "assignment name must be a single directory name, not a path"
            )

        parent_path = Path(parent).expanduser().resolve()
        if not parent_path.exists():
            raise WorkspaceError(f"class directory does not exist: {parent_path}")
        if not parent_path.is_dir():
            raise WorkspaceError(f"class path is not a directory: {parent_path}")

        assignment_candidate = parent_path / name
        if assignment_candidate.is_symlink():
            raise WorkspaceError(
                f"assignment path must not be a symlink: {assignment_candidate}"
            )
        assignment_path = assignment_candidate.resolve()
        try:
            assignment_path.relative_to(parent_path)
        except ValueError as exc:
            raise WorkspaceError(
                f"assignment path is outside class directory: {assignment_path}"
            ) from exc
        if assignment_path.exists() and not assignment_path.is_dir():
            raise WorkspaceError(
                f"assignment path is not a directory: {assignment_path}"
            )
        assignment_path.mkdir(parents=False, exist_ok=True)
        return cls.discover(assignment_path).initialize()

    def inside(self, path: str | Path) -> Path:
        """Resolve a path and prove it stays below the assignment root."""

        candidate = Path(path)
        if not candidate.is_absolute():
            candidate = self.root / candidate
        candidate = candidate.resolve()
        try:
            candidate.relative_to(self.root)
        except ValueError as exc:
            raise WorkspaceError(f"path is outside assignment workspace: {candidate}") from exc
        return candidate

    def ensure_runtime_dirs(self) -> None:
        for relative in (
            ".loop",
            ".loop/sections",
            ".loop/reviews",
            ".loop/logs",
            ".loop/tasks",
            ".loop/agent-results",
            "output",
        ):
            self.inside(relative).mkdir(parents=True, exist_ok=True)

    def initialize(self) -> InitResult:
        """Create the canonical assignment workspace without overwriting input.

        Initialization is intentionally idempotent. Existing assignment input,
        README content, and generated runtime artifacts are preserved, so the
        command is safe to run again after a workspace has been started.
        """

        created: list[str] = []
        existing: list[str] = []

        for relative in INIT_DIRECTORIES:
            path = self.inside(relative)
            if path.exists():
                if not path.is_dir():
                    raise WorkspaceError(f"cannot create directory {relative}: a file already exists")
                existing.append(relative)
                continue
            path.mkdir(parents=True, exist_ok=True)
            created.append(relative)

        for relative, content in INIT_FILES.items():
            path = self.inside(relative)
            if path.exists():
                if not path.is_file():
                    raise WorkspaceError(f"cannot create file {relative}: a directory already exists")
                existing.append(relative)
                continue
            path.write_text(content, encoding="utf-8")
            created.append(relative)

        return InitResult(str(self.root), tuple(created), tuple(existing))

    def relative(self, path: str | Path) -> str:
        return self.inside(path).relative_to(self.root).as_posix()

    def find_input(self, name: str) -> Path | None:
        candidate = self.inside(name)
        return candidate if candidate.is_file() else None

    def outline_index(self) -> dict[str, Any]:
        """Return references for assignment guidance stored under ``outline/``.

        Outline materials are intentionally reference-only. This lets native
        Codex/Work agents inspect Markdown, text, PDF, or other permitted files
        with the tools available in their host environment without making the
        local orchestrator depend on a particular document parser.
        """

        outline_root = self.inside("outline")
        paths: list[Path] = []
        if outline_root.is_dir():
            paths.extend(path for path in outline_root.rglob("*") if path.is_file())

        # Keep existing assignment folders usable while the outline/ folder is
        # adopted. These are compatibility inputs, not the canonical layout.
        for name in ("outline.md", "outline.pdf", "outline.txt", "rubric.md", "rubric.pdf", "rubric.txt"):
            candidate = self.find_input(name)
            if candidate is not None:
                paths.append(candidate)

        unique_paths: list[Path] = []
        seen: set[Path] = set()
        for path in sorted(paths, key=lambda item: self.relative(item)):
            resolved = path.resolve()
            if resolved not in seen:
                seen.add(resolved)
                unique_paths.append(resolved)

        groups: dict[str, Any] = {
            "outline_files": [],
            "assignment_outline_files": [],
            "rubric_files": [],
            "past_marks_files": [],
            "other_guidance_files": [],
            "legacy_files": [],
        }
        for path in unique_paths:
            relative = self.relative(path)
            groups["outline_files"].append(relative)
            if path.parent == self.root:
                groups["legacy_files"].append(relative)
            for category in self._outline_categories(path.stem):
                groups[category].append(relative)

        groups["outline_dir"] = "outline" if outline_root.is_dir() else None
        groups["past_mark_guidance"] = {
            "purpose": "Use prior professor feedback and lost-mark records as preventive guidance.",
            "must_do": [
                "Read every listed past-mark or feedback artifact before planning or drafting.",
                "Extract recurring, concrete reasons marks were lost and turn them into do/not-do checks.",
                "Apply those checks in section plans, writing, and review decisions when they do not conflict with the current assignment.",
            ],
            "must_not_do": [
                "Do not treat historical feedback as a replacement for the current assignment outline or rubric.",
                "Do not invent past mistakes or assume an issue applies when the records do not support it.",
                "Do not copy prior assignment content; use the records only to improve compliance and quality.",
            ],
        }
        return groups

    def _outline_categories(self, stem: str) -> list[str]:
        normalized = re.sub(r"[^a-z0-9]+", "-", stem.lower())
        categories: list[str] = []
        if any(
            token in normalized
            for token in ("past", "previous", "feedback", "deduction", "lost", "comment", "professor")
        ):
            categories.append("past_marks_files")
        if any(token in normalized for token in ("rubric", "grading", "marking", "criteria")):
            categories.append("rubric_files")
        if any(token in normalized for token in ("outline", "brief", "requirement", "instruction", "prompt", "assignment")):
            categories.append("assignment_outline_files")
        return categories or ["other_guidance_files"]

    def input_manifest(self) -> dict[str, Any]:
        """Return references only; content remains in the source workspace."""

        assignment = self.find_input("assignment.md")
        if assignment is None:
            raise WorkspaceError(
                "assignment.md is required in the active assignment directory"
            )
        outline_index = self.outline_index()
        assignment_outline_files = outline_index["assignment_outline_files"]
        rubric_files = outline_index["rubric_files"]

        source_root = self.inside("sources")
        links_path = self.inside("sources/links.md")
        if not links_path.is_file():
            raise WorkspaceError("sources/links.md is required in the active assignment directory")

        source_artifacts = sorted(
            (path for path in source_root.rglob("*") if path.is_file()),
            key=lambda item: self.relative(item),
        )
        unsupported = [
            self.relative(path)
            for path in source_artifacts
            if path.resolve() != links_path.resolve()
            and path.suffix.lower() not in self.SOURCE_FEEDBACK_EXTENSIONS
        ]
        if unsupported:
            supported = ", ".join(sorted(self.SOURCE_FEEDBACK_EXTENSIONS))
            raise WorkspaceError(
                "unsupported file(s) in sources/: "
                f"{', '.join(unsupported)}; optional source feedback must use {supported}"
            )

        source_feedback_files = [
            self.relative(path)
            for path in source_artifacts
            if path.resolve() != links_path.resolve()
        ]
        source_files = [self.relative(links_path)]
        source_artifact_refs = [self.relative(path) for path in source_artifacts]

        return {
            "workspace_root": str(self.root),
            "assignment_file": self.relative(assignment),
            # Singular fields remain as a compatibility convenience for older
            # consumers; the collection fields are authoritative.
            "outline_file": assignment_outline_files[0] if assignment_outline_files else None,
            "rubric_file": rubric_files[0] if rubric_files else None,
            "outline_dir": outline_index["outline_dir"],
            "outline_files": outline_index["outline_files"],
            "assignment_outline_files": assignment_outline_files,
            "rubric_files": rubric_files,
            # Historical grades/feedback belong in sources/ alongside the
            # canonical links file. Keep outline history visible for older
            # assignment layouts, but expose the source-folder files
            # separately so they cannot be mistaken for citation sources.
            "past_marks_files": [
                *outline_index["past_marks_files"],
                *source_feedback_files,
            ],
            "other_guidance_files": outline_index["other_guidance_files"],
            "legacy_outline_files": outline_index["legacy_files"],
            "source_files": source_files,
            "source_dir": "sources",
            "links_file": self.relative(links_path),
            "source_feedback_files": source_feedback_files,
            "source_artifacts": source_artifact_refs,
        }

    def source_index(self) -> list[dict[str, Any]]:
        manifest = self.input_manifest()
        links_file = manifest["links_file"]
        links_text = self.read_input(links_file)
        links = self._extract_urls(links_text)
        if not links:
            raise WorkspaceError("sources/links.md must contain at least one HTTP(S) source link")

        result: list[dict[str, Any]] = []
        for index, link in enumerate(links, start=1):
            title = self._link_title(links_text, link)
            result.append(
                {
                    "id": f"S{index:02d}",
                    "title": title,
                    "authors": [],
                    "year": None,
                    "type": "web",
                    "path": links_file,
                    "url": link,
                    "verified": True,
                }
            )
        return result

    @classmethod
    def _extract_urls(cls, text: str) -> list[str]:
        """Extract unique HTTP(S) URLs while preserving links.md order."""

        urls: list[str] = []
        seen: set[str] = set()
        for match in cls._URL_RE.finditer(text):
            url = match.group(0).rstrip(".,;:!?\"'")
            parsed = urlparse(url)
            if not parsed.netloc:
                continue
            if url not in seen:
                seen.add(url)
                urls.append(url)
        return urls

    @classmethod
    def _link_title(cls, text: str, url: str) -> str:
        for match in cls._MARKDOWN_LINK_RE.finditer(text):
            candidate = match.group(1).rstrip(".,;:!?\"'")
            if candidate == url:
                label = re.sub(r"\s+", " ", match.group(0).split("](", 1)[0][1:]).strip()
                if label:
                    return label
        parsed = urlparse(url)
        hostname = parsed.netloc.removeprefix("www.")
        path_name = parsed.path.rstrip("/").rsplit("/", 1)[-1]
        fallback = path_name or hostname or url
        return re.sub(r"[-_]+", " ", fallback).strip().title()

    def read_input(self, relative: str | Path) -> str:
        path = self.inside(relative)
        try:
            return path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            return ""
